In [1]:
import numpy as np

my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((4,5)) # 4line, 5col, value=0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,4)) # 3line, 4col, value=1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [9]:
np.linspace(0,20,50) # trong khoang value tu 0-20 chia deu cho 50 so

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

## eye

Creates an identity matrix

In [10]:
print("k=0 default hang cheo 1 chinh giua")
print(np.eye(5))
print()

print("k=3")
print(np.eye(5, k=3))

print()
print("k=-2")
print(np.eye(5, k=-2))

k=0 default hang cheo 1 chinh giua
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

k=3
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

k=-2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [11]:
np.random.rand(5) # 5 item

array([0.85457419, 0.05600969, 0.25962323, 0.04996398, 0.94699356])

In [12]:
np.random.rand(3,5) # 3 lines , 5 cols, int duong

array([[0.38428997, 0.03706456, 0.97825879, 0.11669661, 0.28082025],
       [0.62518941, 0.72685303, 0.79490001, 0.44716651, 0.93664503],
       [0.01081789, 0.00678343, 0.30957354, 0.26062663, 0.96617615]])

In [13]:
np.random.randn(5) # 5 items +-

array([ 0.10170118,  1.18292013,  1.25575899, -1.73786552,  0.69152043])

In [14]:
np.random.randn(3,5) # 3 lines, 5 cols +-

array([[-0.12810799, -0.5355762 , -0.43275058,  0.12490863,  1.9310023 ],
       [ 3.05919879,  1.08557109,  1.50475751,  0.51944761,  0.83938406],
       [ 0.48976706, -0.92145815, -0.49749178,  1.32715783, -0.33888155]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [15]:
np.random.randint(1,100)

28

In [16]:
np.random.randint(1,100,10)

array([26, 60, 42, 22, 26, 44, 52, 23, 52, 41])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.

In [19]:
arr.reshape(5,5) # 5 lines, 5 cols phai bang voi so items truoc do la 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [20]:
ranarr = np.random.randint(0,50,10) #size=10 items
ranarr

array([27, 28, 34,  4,  7, 32, 48, 26,  0, 25])

In [21]:
ranarr.max()

48

In [22]:
ranarr.argmax()

6

In [23]:
ranarr.min()

0

In [24]:
ranarr.argmin()

8

In [25]:
# Vector
arr.shape

(25,)

In [26]:
np.array(my_list)

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((4,5)) # 4line, 5col, value=0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones((3,4)) # 3line, 4col, value=1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [35]:
np.linspace(0,20,50) # trong khoang value tu 0-20 chia deu cho 50 so

## eye

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [36]:
#Creates an identity matrix

print("k=0 default hang cheo 1 chinh giua")
print(np.eye(5))
print()

print("k=3")
print(np.eye(5, k=3))

print()
print("k=-2")
print(np.eye(5, k=-2))

k=0 default hang cheo 1 chinh giua
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

k=3
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

k=-2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [37]:
np.random.rand(5) # 5 item

array([0.88611419, 0.59969747, 0.73052173, 0.14614885, 0.34739619])

In [38]:
np.random.rand(3,5) # 3 lines , 5 cols, int duong

array([[0.11459176, 0.02625068, 0.29520478, 0.13414498, 0.0123675 ],
       [0.94464185, 0.79221544, 0.7906093 , 0.15161885, 0.49501034],
       [0.93103799, 0.00959635, 0.13192206, 0.46574451, 0.75321404]])

In [39]:
np.random.randn(5) # 5 items +-

array([-0.96859566, -0.01368305, -1.4237628 ,  0.59375777, -0.84738807])

In [40]:
np.random.randn(3,5) # 3 lines, 5 cols +-

### randint

array([[-0.16352547, -0.31765466, -0.8367967 ,  0.23224447, -0.17067972],
       [-0.31147632, -1.00096139,  0.7042284 ,  0.67664065,  0.04170584],
       [-0.42877948, -0.37691455,  0.53599921, -0.51199918,  0.16110062]])

In [41]:
np.random.randint(1,100)

22

In [42]:
np.random.randint(1,100,10)

array([98,  5, 93, 43, 10, 13, 97, 83, 84, 44])

In [43]:
arr = np.arange(25)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5) # 5 lines, 5 cols phai bang voi so items truoc do la 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr = np.random.randint(0,50,10) #size=10 items
ranarr

array([13, 27, 13, 23, 23, 43,  7,  8, 44, 43])

In [46]:
ranarr.max()

44

In [47]:
ranarr.argmax()

8

In [48]:
ranarr.min()

7

In [49]:
ranarr.argmin()

6

In [50]:
# Vector
arr.shape

(25,)

In [51]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
arr.reshape(1,25).shape

(1, 25)

In [53]:
arr.reshape(25,1) # 25 lines, moi line 1 col

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(25,1).shape

(25, 1)

In [55]:
arr.dtype

dtype('int64')

In [56]:
#slice
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[1,0]

20

In [59]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])