In [1]:
import numpy as np

my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((4,5)) # 4line, 5col, value=0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,4)) # 3line, 4col, value=1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [9]:
np.linspace(0,20,50) # trong khoang value tu 0-20 chia deu cho 50 so

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

## eye

Creates an identity matrix

In [10]:
print("k=0 default hang cheo 1 chinh giua")
print(np.eye(5))
print()

print("k=3")
print(np.eye(5, k=3))

print()
print("k=-2")
print(np.eye(5, k=-2))

k=0 default hang cheo 1 chinh giua
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

k=3
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

k=-2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [11]:
np.random.rand(5) # 5 item

array([0.52688642, 0.59046362, 0.57432968, 0.55165531, 0.4446583 ])

In [12]:
np.random.rand(3,5) # 3 lines , 5 cols, int duong

array([[0.92572898, 0.29767492, 0.93354778, 0.1720908 , 0.69342064],
       [0.57671178, 0.2685191 , 0.2425143 , 0.12207333, 0.19742335],
       [0.78471978, 0.17160484, 0.45396693, 0.75493456, 0.65848716]])

In [13]:
np.random.randn(5) # 5 items +-

array([ 1.72946427, -1.95048188,  1.10438642,  0.46222202,  1.36278483])

In [14]:
np.random.randn(3,5) # 3 lines, 5 cols +-

array([[ 0.99558422, -0.41682963,  0.82742414, -0.27719759,  0.39010121],
       [-0.74564968,  0.63702978,  1.05722058,  0.42138027,  0.65369193],
       [-1.23281947, -1.25137803, -0.18398384, -0.1919845 , -0.64732159]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [15]:
np.random.randint(1,100)

35

In [16]:
np.random.randint(1,100,10)

array([76, 29, 93, 33, 55,  2,  7, 41, 53, 48])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.

In [19]:
arr.reshape(5,5) # 5 lines, 5 cols phai bang voi so items truoc do la 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr = np.random.randint(0,50,10) #size=10 items
ranarr

array([12, 47, 20,  5, 10, 20, 25, 29,  7, 47])

In [21]:
ranarr.max()

47

In [22]:
ranarr.argmax()

1

In [23]:
ranarr.min()

5

In [24]:
ranarr.argmin()

3

In [25]:
arr.shape # tuple(rows, cols) or tuple(len_items,)

(25,)

In [26]:
np.array(my_list)

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((4,5)) # 4line, 5col, value=0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones((3,4)) # 3line, 4col, value=1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [35]:
np.linspace(0,20,50) # trong khoang value tu 0-20 chia deu cho 50 so

## eye

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [36]:
#Creates an identity matrix

print("k=0 default hang cheo 1 chinh giua")
print(np.eye(5))
print()

print("k=3")
print(np.eye(5, k=3))

print()
print("k=-2")
print(np.eye(5, k=-2))

k=0 default hang cheo 1 chinh giua
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

k=3
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

k=-2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [37]:
np.random.rand(5) # 5 item

array([0.44455469, 0.23419661, 0.65817631, 0.93338969, 0.23610682])

In [38]:
np.random.rand(3,5) # 3 lines , 5 cols, int duong

array([[0.51295561, 0.25052763, 0.4977426 , 0.23883521, 0.14664666],
       [0.61674967, 0.86293845, 0.33806642, 0.39903154, 0.21498969],
       [0.25572188, 0.61493614, 0.19304073, 0.74312691, 0.5773733 ]])

In [39]:
np.random.randn(5) # 5 items +-

array([ 1.3563189 , -1.19700026, -1.99819399, -0.01925282, -1.15701586])

In [40]:
np.random.randn(3,5) # 3 lines, 5 cols +-

### randint

array([[ 0.09187596, -1.14848695,  0.45802739,  2.28650821, -1.54776863],
       [-1.24484037, -0.13322081, -0.25082816,  0.26828257, -1.44513518],
       [-1.07096266, -0.72897128, -0.59245344,  1.26608564, -0.07362376]])

In [41]:
np.random.randint(1,100)

44

In [42]:
np.random.randint(1,100,10)

array([41, 71, 36, 96, 91, 75, 31, 62, 78, 89])

In [43]:
arr = np.arange(25)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5) # 5 lines, 5 cols phai bang voi so items truoc do la 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr = np.random.randint(0,50,10) #size=10 items
ranarr

array([ 5,  7, 41,  5, 35,  0, 32, 36, 43, 11])

In [46]:
ranarr.max()

43

In [47]:
ranarr.argmax()

8

In [48]:
ranarr.min()

0

In [49]:
ranarr.argmin()

5

In [50]:
# Vector
arr.shape

(25,)

In [51]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
arr.reshape(1,25).shape

(1, 25)

In [53]:
arr.reshape(25,1) # 25 lines, moi line 1 col

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(25,1).shape

(25, 1)

In [55]:
arr.dtype

dtype('int64')