In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show

def get_names(arr):
    name_attrs = [attr for attr in dir(arr) if not callable(getattr(arr,attr))]
    return name_attrs
    
def get_attrs(arr):
    mapping = {attr: getattr(arr, attr) for attr in get_names(arr)}
    return mapping

get_attrs(arr)


{'T': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 '__array_finalize__': None,
 '__array_interface__': {'data': (21883344, False),
  'strides': None,
  'descr': [('', '<i8')],
  'typestr': '<i8',
  'shape': (11,),
  'version': 3},
 '__array_priority__': 0.0,
 '__array_struct__': <capsule object NULL at 0x7fae1c816f30>,
 '__doc__': None,
 '__hash__': None,
 'base': None,
 'ctypes': <numpy.core._internal._ctypes at 0x7fae1c816f70>,
 'data': <memory at 0x7fae1c8af7c0>,
 'dtype': dtype('int64'),
 'flags':   C_CONTIGUOUS : True
   F_CONTIGUOUS : True
   OWNDATA : True
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False,
 'flat': <numpy.flatiter at 0x1682e30>,
 'imag': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'itemsize': 8,
 'nbytes': 88,
 'ndim': 1,
 'real': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 'shape': (11,),
 'size': 11,
 'strides': (8,)}

In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [15]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [16]:

arr_2d[1,0]

20

In [17]:
# 2D array slicing

print(arr_2d)
#Shape (2,2) from top right corner
arr_2d[:2,1:]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [18]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [19]:
# line 2 lay full cols
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [20]:
#Set up matrix
arr2d = np.zeros((10,10))

In [21]:
#Length of array
arr_length = arr2d.shape[1]
print(f"{arr2d.shape = }")
print(f"{arr_length = }")

arr2d.shape = (10, 10)
arr_length = 10


In [22]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [23]:
arr2d[[2,4,6,8,9]] # row2 full cols, row4 full cols, ...
#arr2d[[row2, row3, row3, ...]] voi full cols

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [24]:
# lay elements cua tung rows tuy y
arr2d = np.random.randint(1,11,(6,4))
arr2d

array([[ 8,  5,  5,  1],
       [ 9,  4,  7,  7],
       [ 5, 10,  3,  6],
       [ 9,  4,  1, 10],
       [ 9,  1,  7,  7],
       [ 7,  4,  4,  3]])

In [25]:
arr2d[[1,3,5], [2,1,3]]
# row1 col2, row3 col1, row5 col3

array([7, 4, 3])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [26]:
arr = np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr>4

In [30]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
print(f"{arr = }")
arr[bool_arr]

arr = array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])